version: 2
jobs:
  build:
    docker:
      - image: docker:git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            docker build -t $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH .
      - run:
          name: Push DockerHub
          command: |
            if [ $(echo $CIRCLE_BRANCH | grep -c "^pull/") -eq 0 ]; then
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
            else
              echo "Pull Request Fork, nothing to do here"
            fi
      - run:
          name: Tag latest
          command: |
            echo "$CIRCLE_TAG -- $CIRCLE_BRANCH"
            if [ -n "$CIRCLE_TAG" ]; then
              docker pull $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH
              docker tag $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:$CIRCLE_BRANCH $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
              echo "$DOCKER_PASS" | docker login -u "$DOCKER_USER" --password-stdin
              docker push $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME:latest
            else
              echo "Not a tag, nothing to do here"
            fi
